config:
  cwd: './external'

product:

  name: "product"
  cores:
    main_core:
      name: 'main'
      device: 'serial'
      exec_path: '/dev/ttyACM0'
      exec_args: '115200,n,8,1'
      conf_path: './external/nuttx/.config'
      elf_path: './external/nuttx/nuttx'
